micronaut:
  application:
    name: demoKafka
netty:
  default:
    allocator:
      max-order: 3
kafka:
  producers:
    default:
      retries: 1
  bootstrap:
    servers: localhost:9092

datasources:
  default:
    url: jdbc:mysql://localhost:3306/dummydb
    username: mahmoud
    password: password
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

flyway:
  datasource:
    default:
      enabled: true