micronaut:
  application:
    name: demo
netty:
  default:
    allocator:
      max-order: 3


hello:
  world:
    message: "Hello from Configuration"
    transaltion:
      de: "Hallo"
      en: "Hello"
